name: morpheus-graphql-uhh-example
version: 0.1.0
github: "nalchevanidze/morpheus-graphql-uhh-example"
license: MIT
author: "Daviti Nalchevanidze"
category: web, graphql
synopsis: examples
copyright: "(c) 2019 Daviti Nalchevanidze"
description: Examples of GraphQL APIs

dependencies:
  - base                            >= 4.7       && <  5
  - text                            >= 1.2.3.0   && <  1.3
  - mtl                             >= 2.0       && <= 2.3
  - morpheus-graphql                >= 0.17.0
  - morpheus-graphql-core           >= 0.17.0
  - morpheus-graphql-app            >= 0.17.0
  - scotty
  - warp

executables:
  uhh-example-server:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
